//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIDA.Master.Service.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIDA.Master.Service.Localizations.StaticMessage", typeof(StaticMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to akses ditolak..
        /// </summary>
        public static string ERR_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ERR_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supervisor aktif NIK {0} tidak ditemukan.
        /// </summary>
        public static string ERR_ACTIVE_FSS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ACTIVE_FSS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salesman aktif NIK {0} tidak ditemukan.
        /// </summary>
        public static string ERR_ACTIVE_SLM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ACTIVE_SLM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector {0} tidak aktif.
        /// </summary>
        public static string ERR_COLLECTOR_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_COLLECTOR_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector {0} tidak ditemukan.
        /// </summary>
        public static string ERR_COLLECTOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_COLLECTOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kosong.
        /// </summary>
        public static string ERR_COLUMN_EMPTY {
            get {
                return ResourceManager.GetString("ERR_COLUMN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer {0} tidak aktif.
        /// </summary>
        public static string ERR_CUSTOMER_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_CUSTOMER_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer {0} tidak ditemukan.
        /// </summary>
        public static string ERR_CUSTOMER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CUSTOMER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data tidak ditemukan..
        /// </summary>
        public static string ERR_DATA_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_DATA_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturis {0} tidak aktif.
        /// </summary>
        public static string ERR_FAKTURIS_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_FAKTURIS_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturis {0} tidak ditemukan.
        /// </summary>
        public static string ERR_FAKTURIS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_FAKTURIS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0} tidak aktif.
        /// </summary>
        public static string ERR_FSS_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_FSS_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSS {0} tidak ditemukan.
        /// </summary>
        public static string ERR_FSS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_FSS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terjadi kesalahan sistem..
        /// </summary>
        public static string ERR_GLOBAL {
            get {
                return ResourceManager.GetString("ERR_GLOBAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid input..
        /// </summary>
        public static string ERR_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERR_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row excel tidak valid.
        /// </summary>
        public static string ERR_INVALID_ROW_XLS {
            get {
                return ResourceManager.GetString("ERR_INVALID_ROW_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username atau password salah..
        /// </summary>
        public static string ERR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIK {0} sudah ada pada master data.
        /// </summary>
        public static string ERR_NIK_EXIST {
            get {
                return ResourceManager.GetString("ERR_NIK_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terdapat {0} baris data tidak valid.
        /// </summary>
        public static string ERR_PREVIEW_CONTAINS_ERROR {
            get {
                return ResourceManager.GetString("ERR_PREVIEW_CONTAINS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role user tidak valid..
        /// </summary>
        public static string ERR_ROLE_INVALID {
            get {
                return ResourceManager.GetString("ERR_ROLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gagal menyimpan data..
        /// </summary>
        public static string ERR_SAVE_FAILED {
            get {
                return ResourceManager.GetString("ERR_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sesi login habis..
        /// </summary>
        public static string ERR_SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("ERR_SESSION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLM {0} tidak aktif.
        /// </summary>
        public static string ERR_SLM_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_SLM_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLM {0} tidak ditemukan.
        /// </summary>
        public static string ERR_SLM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SLM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPV Fakturis {0} tidak aktif.
        /// </summary>
        public static string ERR_SPV_FAKTURIS_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_SPV_FAKTURIS_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPV Fakturis {0} tidak ditemukan.
        /// </summary>
        public static string ERR_SPV_FAKTURIS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SPV_FAKTURIS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user tidak aktif, silahkan hubungi administrator..
        /// </summary>
        public static string ERR_USER_INACTIVE {
            get {
                return ResourceManager.GetString("ERR_USER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user tidak ditemukan..
        /// </summary>
        public static string ERR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to berhasil menambahkan {0} - {1} pada master data.
        /// </summary>
        public static string SCS_ADD_MASTER {
            get {
                return ResourceManager.GetString("SCS_ADD_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to berhasil update {0} - {1}.
        /// </summary>
        public static string SCS_EDIT {
            get {
                return ResourceManager.GetString("SCS_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to berhasil upload {0} baris data..
        /// </summary>
        public static string SCS_IMPORT {
            get {
                return ResourceManager.GetString("SCS_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload berhasil, ditemukan {0} data double.
        /// </summary>
        public static string SCS_IMPORT_FOUND_DOUBLE {
            get {
                return ResourceManager.GetString("SCS_IMPORT_FOUND_DOUBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload berhasil, tidak ada data double..
        /// </summary>
        public static string SCS_IMPORT_NO_DOUBLE {
            get {
                return ResourceManager.GetString("SCS_IMPORT_NO_DOUBLE", resourceCulture);
            }
        }
    }
}
